### ISSUE TITLE
[Crash]: Game doesn't boot

### ISSUE THREAD

**Issue by jonasCCa** [AbdElAziz333/Smooth-Boot-Reloaded#1]
Game doesn't boot even if this is the only mod.

Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Report:

[crash-2022-06-16_15.57.41-client.txt](https://github.com/AbdElAziz333/Smooth-Boot-Reloaded/files/8921682/crash-2022-06-16_15.57.41-client.txt)

**Comment by AbdElAziz333** [comment]
Fixed in the updated version, can be found here :
https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded/files/3837092
Thanks!
